const ADD_INITIAL_VALUE = 'ADD_INITIAL_VALUE'
const NAVIGATE_TO = 'NAVIGATE_TO'
const CHANGE_MAIN_WINDOW = 'CHANGE_MAIN_WINDOW'
const CLEAR_STATE = 'CLEAR_STATE'
const SHOW_PRODUCT_GROUPS_MODAL = 'SHOW_PRODUCT_GROUPS_MODAL'
const SHOW_CLIENT_MODAL = 'SHOW_CLIENT_MODAL'
const SHOW_PRODUCT_MODAL = 'SHOW_PRODUCT_MODAL'

export {
	ADD_INITIAL_VALUE,
	NAVIGATE_TO,
	CHANGE_MAIN_WINDOW,
	CLEAR_STATE,
	SHOW_PRODUCT_GROUPS_MODAL,
	SHOW_CLIENT_MODAL,
	SHOW_PRODUCT_MODAL
}
